language: scala
sudo: false
scala:
  - 2.11.5
jdk:
  - oraclejdk7
  - openjdk7
notifications:
  email: false
  webhooks:
    urls:
      - https://whispering-sands-84094.herokuapp.com/telegram-bot/travisci/37798333
    on_start: always